accounts/urls.py
from django.urls import path
from . import views

app_name =  "accounts"

urlpatterns = [
    path("login/", views.login_view, name = "login")
]

core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name = "index"),
    path("post/<int:id>", views.post, name = "post"),
    path("profile/<int:id>", views.profile, name = "profile")
]

urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pinterest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls"))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    photo = models.ImageField(default= "core/img/av.png", upload_to = "core/img/userslogo")    
    email = models.EmailField(max_length=254)

core/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 24)
    description = models.CharField(max_length=512)
    photo = models.ImageField(upload_to="core/img/")
    viewed = models.IntegerField(default = 0)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.title} by {self.user}"
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)

    def __str__(self):
        return f"like on {self.post} "
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    text = models.TextField(max_length = 1024)

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login

from .models import User

# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("core:index"))
    if request.method == "POST":

        # Attempt to sign user in
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        print(user)
        print(User.objects.get(email = email))
        # Check if authentication successful
        if user is not None:
            
            login(request, user)
            return HttpResponseRedirect(reverse("core:index"))
        else:
            return render(request, "accounts/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "accounts/login.html")
    return render(request, "accounts/login.html")

def register_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "accounts/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "accounts/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("core:index"))
    else:
        return render(request, "accounts/register.html")
    return render(request, "accounts/register.html")

def logout(request):
    pass

api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework import status


class PostModelView(APIView):
    permission_clases = [IsAuthenticated]
    #getting all Posts
    def get(self, request):
       pass

    #creating a Post
    def post(self, request):
       pass

    #Update Post
    def put(self, request, id):
        
       pass
        

    #Delete Post
    def delete(self, request, id):
        
        pass
    

core/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .utils import update_view_counter
from .models import Post

# Create your views here.
@login_required(login_url = settings.LOGIN_URL)
def index(request):
    posts = Post.objects.all()
    context = {"posts":posts}
    return render(request, "core/index.html", context)

def post(request, id):
    post = Post.objects.get(id = id)
    update_view_counter(post)
    context = {"post":post}
    return render(request, "core/post.html", context)

def profile(request, id):
    user = User.objects.get(id = id)

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pinterest Login</title>
  <link rel="stylesheet" href="{% static "accounts/css/styles.css" %}">
</head>
<body>
  <div class="container">
    <div class="header">
      <img src="{% static "core/img/logo.png" %}" alt="Pinterest Logo">
      <h1>Log in to Pinterest</h1>
    </div>

    <form action="{% url "accounts:login" %}" method = "POST">
      {% csrf_token %}
      <label for="email">Email Address:</label>
      <input type="email" id="email" name = "email" placeholder="Enter your email address">

      <label for="password">Password:</label>
      <input type="password" name = "password" id="password" placeholder="Enter your password">

      <button type="submit">Log in</button>
      {{message}}
      <p>
        <a href="#">Forgot your password?</a>
      </p>
    </form>

    <p class="or">OR</p>

    <div class="social-buttons">
      <a href="#" class="btn fb"><i class="fab fa-facebook fa-lg"></i> Sign in with Facebook</a>
      <a href="#" class="btn gg"><i class="fab fa-google fa-lg"></i> Sign in with Google</a>
    </div>

    <p>
      Don't have an account?
      <a href="#">Create an account</a>
    </p>
  </div>
</body>
</html>

accounts/templates/accounts/nickname.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pinterest Login</title>
  <link rel="stylesheet" href="{% static "accounts/css/styles.css" %}">
</head>
<body>
  <div class="container">
    <div class="header">
      <img src="{% static "core/img/logo.png" %}" alt="Pinterest Logo">
      <h1>Log in to Pinterest</h1>
    </div>

    <form action="">
      <label for="email">Email Address:</label>
      <input type="email" id="email" name = "email" placeholder="Enter your email address">

      <label for="password">Password:</label>
      <input type="password" name = "password" id="password" placeholder="Enter your password">

      <button type="submit">Log in</button>
      {{message}}
      <p>
        <a href="#">Forgot your password?</a>
      </p>
    </form>

    <p class="or">OR</p>

    <div class="social-buttons">
      <a href="#" class="btn fb"><i class="fab fa-facebook fa-lg"></i> Sign in with Facebook</a>
      <a href="#" class="btn gg"><i class="fab fa-google fa-lg"></i> Sign in with Google</a>
    </div>

    <p>
      Don't have an account?
      <a href="#">Create an account</a>
    </p>
  </div>
</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pinterest Login</title>
  <link rel="stylesheet" href="{% static "accounts/css/styles.css" %}">
</head>
<body>
  <div class="container">
    <div class="header">
      <img src="{% static "core/img/logo.png" %}" alt="Pinterest Logo">
      <h1>Log in to Pinterest</h1>
    </div>

    <form action="">
      <label for="email">Email Address:</label>
      <input type="email" id="email" name = "email" placeholder="Enter your email address">

      <label for="password">Password:</label>
      <input type="password" name = "password" id="password" placeholder="Enter your password">

      <button type="submit">Log in</button>
      {{message}}
      <p>
        <a href="#">Forgot your password?</a>
      </p>
    </form>

    <p class="or">OR</p>

    <div class="social-buttons">
      <a href="#" class="btn fb"><i class="fab fa-facebook fa-lg"></i> Sign in with Facebook</a>
      <a href="#" class="btn gg"><i class="fab fa-google fa-lg"></i> Sign in with Google</a>
    </div>

    <p>
      Don't have an account?
      <a href="#">Create an account</a>
    </p>
  </div>
</body>
</html>

core/templates/core/index.html
{% extends "core/layout.html" %}
{% block body %}


        
    
    <section class="mt-4 mb-5">
    <div class="container mb-4">
    	<h1 class="font-weight-bold title">Explore</h1>
    	<div class="row">
    		<nav class="navbar navbar-expand-lg navbar-light bg-white pl-2 pr-2">
    		<button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExplore" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
    		</button>
    		<div class="collapse navbar-collapse" id="navbarsExplore">
    			<ul class="navbar-nav">
    				<li class="nav-item">
    				<a class="nav-link" href="#">Lifestyle</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Food</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Home</a>
    				</li>
    				<li class="nav-item">
    				<a class="nav-link" href="#">Travel</a>
    				</li>
    				<li class="nav-item dropdown">
    				<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">More</a>
    				<div class="dropdown-menu shadow-lg" aria-labelledby="dropdown01">
    					<a class="dropdown-item" href="#">Astronomy</a>
    					<a class="dropdown-item" href="#">Nature</a>
    					<a class="dropdown-item" href="#">Cooking</a>
    					<a class="dropdown-item" href="#">Fashion</a>
    					<a class="dropdown-item" href="#">Wellness</a>
    					<a class="dropdown-item" href="#">Dieting</a>
    				</div>
    				</li>
    			</ul>
    		</div>
    		</nav>
    	</div>
    </div>
    <div class="container-fluid">
    	<div class="row">
    		<div class="card-columns">
				{% for post in posts %}
				<div class="card card-pin">
    				<img class="card-img" src="{{post.photo.url}}" alt="Card image">
    				<div class="overlay">
    					<h2 class="card-title title">{{post.title}}</h2>
    					<div class="more">
    						<a href="{% url "core:post" post.id%}">
    						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
    					</div>
    				</div>
    			</div>
				{% endfor %}
				
    			
    		</div>
    	</div>
    </div>
    </section>
        


{% endblock body %}



    

core/templates/core/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home - Pintereso Bootstrap Template</title>
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{% static 'core/css/app.css'%}">
    <link rel="stylesheet" href="{% static 'core/css/theme.css'%}">

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <a class="navbar-brand font-weight-bolder mr-3" href="index.html"><img src="{% static 'core/img/logo.png'%}" class="logo"></a>
    <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsDefault">
    	<ul class="navbar-nav mr-auto align-items-center">
    		<form class="bd-search hidden-sm-down">
    			<input type="text" class="form-control bg-graylight border-0 font-weight-bold" id="search-input" placeholder="Search..." autocomplete="off">
    			<div class="dropdown-menu bd-search-results" id="search-results">
    			</div>
    		</form>
    	</ul>
    	<ul class="navbar-nav ml-auto align-items-center">
    		<li class="nav-item">
    		<a class="nav-link active" href="index.html">Home</a>
    		</li>
    		<li class="nav-item">
    		<a class="nav-link" href="post.html">Post</a>
    		</li>
    		<li class="nav-item">
    		<a class="nav-link" href="{% url "core:profile" request.user.id%}"><img class="rounded-circle mr-2" src="{{request.user.photo.url}}" width="30"><span class="align-middle">{{request.user}}</span></a>
    		</li>
    		<li class="nav-item dropdown">
    		<a class="nav-link" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    		<svg style="margin-top:10px;" class="_3DJPT" version="1.1" viewbox="0 0 32 32" width="21" height="21" aria-hidden="false" data-reactid="71"><path d="M7 15.5c0 1.9-1.6 3.5-3.5 3.5s-3.5-1.6-3.5-3.5 1.6-3.5 3.5-3.5 3.5 1.6 3.5 3.5zm21.5-3.5c-1.9 0-3.5 1.6-3.5 3.5s1.6 3.5 3.5 3.5 3.5-1.6 3.5-3.5-1.6-3.5-3.5-3.5zm-12.5 0c-1.9 0-3.5 1.6-3.5 3.5s1.6 3.5 3.5 3.5 3.5-1.6 3.5-3.5-1.6-3.5-3.5-3.5z" data-reactid="22"></path></svg>
    		</a>
    		<div class="dropdown-menu dropdown-menu-right shadow-lg" aria-labelledby="dropdown02">
    			<h4 class="dropdown-header display-4">Download Pintereso<br/> HTML Bootstrap Template</h4>
    			<div class="dropdown-divider">
    			</div>
    			<span class="dropdown-item"><a href="https://github.com/wowthemesnet/template-pintereso-bootstrap-html/archive/master.zip" class="btn btn-primary d-block"><i class="fa fa-download"></i> Download</a></span>
    		</div>
    		</li>
    	</ul>
    </div>
    </nav>    
    <main role="main">
    {% block body %}{% endblock body %}
    </main>

    <script src="{% static 'core/js/app.js'%}"></script>
    <script src="{% static 'core/js/theme.js'%}"></script>
    
    <footer class="footer pt-5 pb-5 text-center">
        
    <div class="container">
        
          <div class="socials-media">
    
            <ul class="list-unstyled">
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-facebook"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-twitter"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-instagram"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-google-plus"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-behance"></i></a></li>
              <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-dribbble"></i></a></li>
            </ul>
    
          </div>
        
            <!--
              All the links in the footer should remain intact.
              You may remove the links only if you donate:
              https://www.wowthemes.net/freebies-license/
            -->
          <p>©  <span class="credits font-weight-bold">        
            <a target="_blank" class="text-dark" href="https://www.wowthemes.net/pintereso-free-html-bootstrap-template/"><u>Pintereso Bootstrap HTML Template</u> by WowThemes.net.</a>
          </span>
          </p>
    
    
        </div>
        
    </footer>    
</body>
    
</html>

core/templates/core/layouts/default.html
{{!-- This is the base layout for your project, and will be used on every page. --}}
<!DOCTYPE html>
<html lang="en">

<head>
    {{!— Required meta tags --}}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}} - Pintereso Bootstrap Template</title>
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>
    <link rel="stylesheet" href="{{root}}assets/css/app.css">
    <link rel="stylesheet" href="{{root}}assets/css/theme.css">

</head>

<body>
    {{!-- Navigation and Footer are in partials folder. The body represents the content pages folder. --}}

    {{> navigation}}
    
    <main role="main">
        
    {{> body}}
        
    </main>

    {{> footer}}
    
</body>
    
</html>

core/templates/core/pages/post.html
---
layout: default
title: Post
---

<section class="bg-gray200 pt-5 pb-5">
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-7">
			<article class="card">
			<img class="card-img-top mb-2" src="https://images.unsplash.com/photo-1490645935967-10de6ba17061?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e0245bb4e87077312cc3d102e68c1efd&auto=format&fit=crop&w=735&q=80" alt="Card image">
			<div class="card-body">
				<h1 class="card-title display-4">
				Sushi Rolls </h1>
				<ul>
					<li>5 cups short-grain sushi rice</li>
					<li>6 cups water</li>
					<li>1/2 cup rice vinegar</li>
					<li>2 tablespoons sugar</li>
					<li>A teaspoon of salt</li>
				</ul>
				<small class="d-block"><a class="btn btn-sm btn-gray200" href="#"><i class="fa fa-external-link"></i> Visit Website</a></small>
				<!-- Begin Comments -replace demowebsite with your own id
                ================================================== -->
				<div id="comments" class="mt-4">
					<div id="disqus_thread">
					</div>
					<script type="text/javascript">
                        var disqus_shortname = 'demowebsite'; 
                        var disqus_developer = 0;
                        (function() {
                            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                            dsq.src = window.location.protocol + '//' + disqus_shortname + '.disqus.com/embed.js';
                            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                        })();
                    </script>
					<noscript>
					Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
					</noscript>
				</div>
				<!--End Comments
                ================================================== -->
			</div>
			</article>
		</div>
	</div>
</div>
<div class="container-fluid mt-5">
	<div class="row">
		<h5 class="font-weight-bold">More like this</h5>
		<div class="card-columns">
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1518707399486-6d702a84ff00?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=b5bb16fa7eaed1a1ed47614488f7588d&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1519408299519-b7a0274f7d67?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d4891b98f4554cc55eab1e4a923cbdb1&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1506706435692-290e0c5b4505?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0bb464bb1ceea5155bc079c4f50bc36a&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1512355144108-e94a235b10af?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c622d56d975113a08c71c912618b5f83&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1518542331925-4e91e9aa0074?ixlib=rb-0.3.5&s=6958cfb3469de1e681bf17587bed53be&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1513028179155-324cfec2566c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=32ce1df4016dadc177d6fce1b2df2429&auto=format&fit=crop&w=350&q=80" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1516601255109-506725109807?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ce4f3db9818f60686e8e9b62d4920ce5&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1505210512658-3ae58ae08744?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=2ef2e23adda7b89a804cf232f57e3ca3&auto=format&fit=crop&w=333&q=80" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1488353816557-87cd574cea04?ixlib=rb-0.3.5&s=06371203b2e3ad3e241c45f4e149a1b3&auto=format&fit=crop&w=334&q=80" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
			<div class="card card-pin">
				<img class="card-img" src="https://images.unsplash.com/photo-1518450757707-d21c8c53c8df?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c88b5f311958f841525fdb01ab3b5deb&auto=format&fit=crop&w=500&q=60" alt="Card image">
				<div class="overlay">
					<h2 class="card-title title">Some Title</h2>
					<div class="more">
						<a href="post.html">
						<i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> More </a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</section>

core/templates/core/partials/footer.html
<script src="{{root}}assets/js/app.js"></script>
<script src="{{root}}assets/js/theme.js"></script>

<footer class="footer pt-5 pb-5 text-center">
    
<div class="container">
    
      <div class="socials-media">

        <ul class="list-unstyled">
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-facebook"></i></a></li>
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-twitter"></i></a></li>
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-instagram"></i></a></li>
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-google-plus"></i></a></li>
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-behance"></i></a></li>
          <li class="d-inline-block ml-1 mr-1"><a href="#" class="text-dark"><i class="fa fa-dribbble"></i></a></li>
        </ul>

      </div>
    
        <!--
          All the links in the footer should remain intact.
          You may remove the links only if you donate:
          https://www.wowthemes.net/freebies-license/
        -->
      <p>©  <span class="credits font-weight-bold">        
        <a target="_blank" class="text-dark" href="https://www.wowthemes.net/pintereso-free-html-bootstrap-template/"><u>Pintereso Bootstrap HTML Template</u> by WowThemes.net.</a>
      </span>
      </p>


    </div>
    
</footer>